---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
    playbook: php70.yml
    php_version: 7.0
  - distro: debian9
    playbook: php71.yml
    php_version: 7.1
  - distro: debian9
    playbook: php72.yml
    php_version: 7.2

  - distro: debian8
    playbook: php70.yml
    php_version: 7.0
  - distro: debian8
    playbook: php71.yml
    php_version: 7.1
  - distro: debian8
    playbook: php72.yml
    php_version: 7.2

  - distro: ubuntu1804
    playbook: php70.yml
    php_version: 7.0
  - distro: ubuntu1804
    playbook: php71.yml
    php_version: 7.1
  - distro: ubuntu1804
    playbook: php72.yml
    php_version: 7.2

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure PHP is installed and at the right version.
  - ${DOCKER} which php
  - ${DOCKER} test -x /usr/bin/php

  - ${DOCKER} php --version
  - ${DOCKER} /usr/bin/php --version | grep -qF "PHP ${php_version}"

  # Check if socket exists
  - ${DOCKER} test -e /run/travis.socket

  # Check if OpCache is installed
  - ${DOCKER} php -v | grep 'ionCube'

  # Check if ioncube is installed
  - ${DOCKER} php -v | grep 'OPcache'

  # Ensure PHP configurations have taken effect.
  - ${DOCKER} php -i | grep 'memory_limit.*192'

  # Check the status of PHP-FPM.
  - ${DOCKER} systemctl --no-pager status php${php_version}-fpm
  - ${DOCKER} systemctl --no-pager status php${php_version}-fpm | grep 'fpm.service; enabled'

  # Check php extensions
  - ${DOCKER} php -m | grep 'apcu'
  - ${DOCKER} php -m | grep 'bcmath'
  - ${DOCKER} php -m | grep 'calendar'
  - ${DOCKER} php -m | grep 'ctype'
  - ${DOCKER} php -m | grep 'curl'
  - ${DOCKER} php -m | grep 'dom'
  - ${DOCKER} php -m | grep 'exif'
  - ${DOCKER} php -m | grep 'fileinfo'
  - ${DOCKER} php -m | grep 'ftp'
  - ${DOCKER} php -m | grep 'gd'
  - ${DOCKER} php -m | grep 'gettext'
  - ${DOCKER} php -m | grep 'hash'
  - ${DOCKER} php -m | grep 'iconv'
  - ${DOCKER} php -m | grep 'igbinary'
  - ${DOCKER} php -m | grep 'imagick'
  - ${DOCKER} php -m | grep 'intl'
  - ${DOCKER} php -m | grep 'json'
  - ${DOCKER} php -m | grep 'libxml'
  - ${DOCKER} php -m | grep 'mbstring'
  - ${DOCKER} php -m | grep 'mcrypt'
  - ${DOCKER} php -m | grep 'memcached'
  - ${DOCKER} php -m | grep 'mysqli'
  - ${DOCKER} php -m | grep 'mysqlnd'
  - ${DOCKER} php -m | grep 'openssl'
  - ${DOCKER} php -m | grep 'PDO'
  - ${DOCKER} php -m | grep 'pdo_mysql'
  - ${DOCKER} php -m | grep 'pdo_sqlite'
  - ${DOCKER} php -m | grep 'Phar'
  - ${DOCKER} php -m | grep 'redis'
  - ${DOCKER} php -m | grep 'Reflection'
  - ${DOCKER} php -m | grep 'session'
  - ${DOCKER} php -m | grep 'SimpleXML'
  - ${DOCKER} php -m | grep 'soap'
  - ${DOCKER} php -m | grep 'sockets'
  - ${DOCKER} php -m | grep 'SPL'
  - ${DOCKER} php -m | grep 'sqlite3'
  - ${DOCKER} php -m | grep 'standard'
  - ${DOCKER} php -m | grep 'tidy'
  - ${DOCKER} php -m | grep 'tokenizer'
  - ${DOCKER} php -m | grep 'standard'
  - ${DOCKER} php -m | grep 'xml'
  - ${DOCKER} php -m | grep 'xmlreader'
  - ${DOCKER} php -m | grep 'xmlrpc'
  - ${DOCKER} php -m | grep 'xmlwriter'
  - ${DOCKER} php -m | grep 'xsl'
  - ${DOCKER} php -m | grep 'Zend OPcache'
  - ${DOCKER} php -m | grep 'zip'
  - ${DOCKER} php -m | grep 'zlib'

  # Check Zend OpCache already loaded
  - >
    ${DOCKER} php -m | grep 'Cannot load Zend OPcache - it was already loaded'
    && (echo 'Zend OpCache is configured twice' && exit 1)
    || (echo 'Zend OpCache is configured correctly' && exit 0)

after_failure:
  - ${DOCKER} php -v
  - ${DOCKER} php -i | grep 'memory_limit.*'
  - ${DOCKER} php -m
  - ${DOCKER} apt-cache search php*

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/