---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
  - distro: ubuntu1804
    playbook: php70.yml
    php_version: 7.0
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204
  - distro: debian9
    playbook: php70.yml
    php_version: 7.0

  - distro: debian8
    playbook: php70.yml
    php_version: 7.0

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure php is installed.
  - 'docker exec --tty ${container_id} env TERM=xterm php -v | grep "PHP $php_version"'

  # Check if socket exists
  - 'docker exec --tty ${container_id} env TERM=xterm test -e /run/travis.socket'

  # Check if ioncube is installed
  - 'docker exec --tty ${container_id} env TERM=xterm php -v | grep ionCube'

notifications:
   webhooks: https://galaxy.ansible.com/api/v1/notifications/