---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - SITE=php70.yml ANSIBLE_VERSION=latest
  - SITE=php70.yml ANSIBLE_VERSION=2.5.0.0

  - SITE=php71.yml ANSIBLE_VERSION=latest
  - SITE=php71.yml ANSIBLE_VERSION=2.5.0.0

  - SITE=php72.yml ANSIBLE_VERSION=latest
  - SITE=php72.yml ANSIBLE_VERSION=2.5.0.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl
  - sudo apt-get purge -y 'php5*'

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install --no-binary ansible ansible; else pip install --no-binary ansible ansible==$ANSIBLE_VERSION; fi

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install ansible-lint
  - pip install ansible-lint

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/$SITE --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/$SITE --connection=local --become

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # ansible-lint checks for best practice
  - ansible-lint tests/$SITE

  # Check if php is installed
  - >
    sudo php -v
    && (echo 'PHP installed' && exit 0)
    || (echo 'PHP is not installed' && exit 1)

  # Check if socket exists
  - >
    test -e /run/travis.socket
    && (echo 'PHP socket exists' && exit 0)
    || (echo 'PHP socket does not exist' && exit 1)

  - >
    sudo php -v | grep ionCube
    && (echo 'ionCube installed' && exit 0)
    || (echo 'ionCube is not installed' && exit 1)


after_failure:
  # run playbook again to see idempotence failures
  - ansible-playbook -i tests/inventory tests/$SITE --connection=local --become -vvv
  - service php7.0-fpm status
  - sudo php -v
  - 'ls -lg /etc/php/*/fpm/pool.d/*'
  - 'ls -l /run/'
  - sudo tail -n150 /var/log/syslog
  - ansible --version
  - ansible-lint --version
  - sudo ls -l /usr/lib/php7/ioncube/
  - php /var/www/html/index.php

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/